# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20170320_2021'),
        ('organization', '0002_organization_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitrequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='visitrequest',
            name='city',
        ),
        migrations.RemoveField(
            model_name='visitrequest',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='visitrequest',
            name='state',
        ),
        migrations.RemoveField(
            model_name='visitrequest',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointments.Location'),
            preserve_default=False,
        ),
    ]
