# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-02 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170320_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
