# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer_name', models.CharField(max_length=1000, unique=True, verbose_name='Insurer Name')),
                ('insurer_code', models.CharField(max_length=1000, unique=True, verbose_name='Insurer Code')),
                ('copay', models.FloatField(default=0, verbose_name='Co-Pay For Patients')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=1000, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=7, null=True, verbose_name='Zip Code')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Location Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('zipcode', models.CharField(max_length=7, verbose_name='Zip Code')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAppointmentSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Is Booked')),
                ('is_break', models.BooleanField(default=False, verbose_name='Is Break')),
                ('start', models.DateTimeField(verbose_name='Start Time')),
                ('end', models.DateTimeField(verbose_name='End Time')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('reimbursement_confirmed', models.BooleanField(default=False, verbose_name='Insurance Reimbursement Confirmed')),
                ('notes', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Notes')),
                ('billing_sent', models.BooleanField(default=False, verbose_name='Billing Sent to Insurer')),
                ('billing_recieved', models.BooleanField(default=False, verbose_name='Billing Recieved From Insurer')),
                ('is_noshow', models.BooleanField(default=False, verbose_name='No Show')),
                ('upload1', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='File 1')),
                ('upload2', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='File 2')),
                ('upload3', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='File 3')),
                ('addendum_upload1', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Addendum File 1')),
                ('addendum_upload2', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Addendum File 2')),
                ('addendum_upload3', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Addendum File 3')),
                ('is_locked', models.BooleanField(default=False, help_text='WARNING: Once you have locekd an appointment you cannot modify it', verbose_name='Locked')),
                ('lock_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Time Locked')),
                ('addendum_notes', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Addendum Notes')),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start', models.TimeField(verbose_name='Start Time (HH:MM)')),
                ('end', models.TimeField(verbose_name='End Time (HH:MM)')),
                ('duration', models.IntegerField(verbose_name='Duration (Minutes)')),
                ('details', models.TextField(blank=True, max_length=300, null=True, verbose_name='Details (Will be shown to patients)  i.e. come to the conference room')),
                ('is_confirmed', models.BooleanField(default=True)),
                ('rating', models.IntegerField(blank=True, default=None, null=True)),
                ('feedback', models.TextField(blank=True, default=None, null=True, verbose_name='Additional Feedback')),
            ],
        ),
    ]
