# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('hygenist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='hygenist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hygenist.Hygenist', verbose_name='On-Site Hygenist'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Location'),
        ),
    ]
