# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('internal', '0001_initial'),
        ('appointments', '0002_auto_20170320_2021'),
        ('organization', '0002_organization_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointmentslot',
            name='patient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patients.Patient', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='patientappointmentslot',
            name='referred_dentist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internal.ReferredDentist', verbose_name='Refer to Dentist'),
        ),
        migrations.AddField(
            model_name='patientappointmentslot',
            name='sitevisit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.SiteVisit'),
        ),
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='sitevisit',
            unique_together=set([('location', 'date', 'hygenist')]),
        ),
        migrations.AlterUniqueTogether(
            name='patientappointmentslot',
            unique_together=set([('sitevisit', 'start')]),
        ),
    ]
