# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('appointments', '0003_auto_20170320_2021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_organization_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization', verbose_name='Name of Company'),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Insurer', verbose_name='Name of Insurer'),
        ),
    ]
